services:
  redis-1:
    image: redis:8.4-alpine
    ports: ["6381:6379"]
  redis-2:
    image: redis:8.4-alpine
    ports: ["6382:6379"]
  redis-3:
    image: redis:8.4-alpine
    ports: ["6383:6379"]
